### ISSUE TITLE
Program opens properly but no response to button presses when following wiring diagram.  Do I need to edit code or wiring?

### ISSUE THREAD

**Issue by MichaelWoodc** [TheWhite147/pi-score-counter#13]
Thanks for all the previous help!  I was able to get it working on the latest pi OS, up until the button presses.  I followed the diagram, however, is it possible I need 10k resistors?  

Here is my output when I run the program from the terminal:

`** Game started! **
Traceback (most recent call last):
  File "/home/pi/pi-score-counter/game_logic.py", line 7, in <module>
    import MFRC522
  File "/home/pi/pi-score-counter/MFRC522.py", line 25, in <module>
    import spi
ModuleNotFoundError: No module named 'spi'
pi@raspberrypi:~/Desktop $ libEGL warning: DRI2: failed to authenticate
[1565:1565:0803/135312.055472:ERROR:component_loader.cc(189)] Failed to parse extension manifest.
[1617:1617:0803/135312.899416:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is egl, ANGLE is 
[1617:1617:0803/135313.057893:ERROR:viz_main_impl.cc(185)] Exiting GPU process due to errors during initialization
libEGL warning: DRI2: failed to authenticate
[1752:1752:0803/135313.927657:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is egl, ANGLE is 
[1752:1752:0803/135314.066437:ERROR:viz_main_impl.cc(185)] Exiting GPU process due to errors during initialization
[1780:1780:0803/135314.283710:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
[1643:8:0803/135314.316677:ERROR:command_buffer_proxy_impl.cc(125)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.

`

I am wondering if it could  be because the pins listed below, is the "= 16" the pin, or is the commented gpio number the correct one?

GPIO_INPUT_P1BA = 16 # GPIO23 Player 1 - Button A --> Was 12 (GPIO18) before
GPIO_INPUT_P1BB = 18 # GPIO24 Player 1 - Button B
GPIO_INPUT_P2BA = 15 # GPIO22 Player 2 - Button A
GPIO_INPUT_P2BB = 11 # GPIO17 Player 2 - Button B
GPIO_INPUT_RESET = 22 # GPIO25 Reset button

**Comment by TheWhite147** [comment]
Have you installed/enabled everything here: https://github.com/TheWhite147/pi-score-counter#nfc-reader-installation-new-in-140
Even if you don't use the NFC Reader, you need to do these steps.

**Comment by TheWhite147** [comment]
You can also comment lines 382 to 422 in `game_logic.py` if you want to bypass NFC reader logic and avoid further problems.

**Comment by MichaelWoodc** [comment]
You saved my life, can't thank you enough!!!! I got everything working, now I'm just going to edit the code a little and make it also activate relays!  I love it, thanks for the help!

**Comment by TheWhite147** [comment]
I'm glad everything is working well! Have fun! 😄
